steps:
  - name: "node:20"
    entrypoint: bash
    args:
      - -c
      - |
        rm -rf node_modules/.cache
        npm install
    env:
      - "NODE_ENV=production"
      - "NEXT_PUBLIC_WEBSOCKET_URL=${_WEBSOCKET_URL}"
      - "NEXT_PUBLIC_MONGO_URI=${_MONGO_URI}"
      - "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY}"

  - name: "node:20"
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "NODE_ENV=production"
      - "NEXT_PUBLIC_WEBSOCKET_URL=${_WEBSOCKET_URL}"
      - "NEXT_PUBLIC_MONGO_URI=${_MONGO_URI}"
      - "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY}"

  - name: "gcr.io/k8s-skaffold/pack"
    args:
      [
        "build",
        "gcr.io/q-manager-453001/nextjs-q-manager",
        "--builder=gcr.io/buildpacks/builder:v1",
        "--env=NODE_ENV=production",
        "--env=NEXT_PUBLIC_WEBSOCKET_URL=${_WEBSOCKET_URL}",
        "--env=NEXT_PUBLIC_MONGO_URI=${_MONGO_URI}",
        "--env=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY}",
      ]

timeout: "1200s"

images:
  - gcr.io/q-manager-453001/nextjs-q-manager
