name: Deploy Next.js App to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "Dockerfile"
      - "terraform/nextjs/**"
      - ".github/workflows/deploy-nextjs.yml"
      - "!src/websocket-server/**"
      - "!terraform/websocket-server/**"
      - "!.github/workflows/deploy-websocket-server.yml"

env:
  ENVIRONMENT: "qa"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Build Args
        run: |
          echo "BUILD ARGS FROM SECRETS"
          echo "NEXT_PUBLIC_MONGO_URI=${{ secrets.MONGO_URI }}"
          echo "CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Configure Docker to Use Google Cloud Credentials
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "q-manager-453001"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Buildx Builder
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Debug Docker Context
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -al
          docker --version
          docker buildx version

      - name: Clean Cache
        run: |
          rm -rf .next
          rm -rf node_modules/.cache/tailwindcss
          docker builder prune --all --force

      - name: Install Dependencies
        run: npm install --force

      - name: Build and Push Docker Image
        run: |
          echo "Listing files in current context:"
          ls -al

          IMAGE_NAME="asia-southeast1-docker.pkg.dev/q-manager-453001/q-manager-nextjs/nextjs-app:${{ github.sha }}"

          # 🔍 Print each command before executing it
          set -x

          docker buildx build --no-cache --platform=linux/amd64 -t "$IMAGE_NAME" --push -f Dockerfile . \
            --build-arg NEXT_PUBLIC_MONGO_URI="${{ secrets.MONGO_URI }}" \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.CLERK_PUBLISHABLE_KEY }}" \
            --build-arg CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}" \
            --build-arg NEXT_PUBLIC_SOCKET_URL="${{ secrets.SOCKET_URL }}" \
            --build-arg TAILWIND_CONFIG="tailwind.config.ts"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform/nextjs-app
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/nextjs-app
        run: |
          IMAGE_NAME="asia-southeast1-docker.pkg.dev/q-manager-453001/q-manager-nextjs/nextjs-app:${{ github.sha }}"

          terraform apply \
            -var="image_tag=$IMAGE_NAME" \
            -var="project_id=q-manager-453001" \
            -var="region=asia-southeast1" \
            -var="mongo_uri=${{ secrets.MONGO_URI }}" \
            -var="clerk_secret_key=${{ secrets.CLERK_SECRET_KEY }}" \
            -var="clerk_publishable_key=${{ secrets.CLERK_PUBLISHABLE_KEY }}" \
            -var="env=${{ env.ENVIRONMENT }}" \
            -var="socket_url=${{ secrets.SOCKET_URL }}" \
            -var="google_bucket_credentials=${{ secrets.GOOGLE_BUCKET_CREDENTIALS }}" \
            -lock-timeout=90s \
            -auto-approve
