name: Deploy WebSocket Server to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "src/websocket-server/**"
      - "src/terraform/websocket-server/**"
      - ".github/workflows/deploy-websocket-server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      # ✅ Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "q-manager-453001"

      # ✅ Step 4: Build and Push Docker Image to GCR
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="australia-southeast2-docker.pkg.dev/q-manager-453001/q-manager-websocket-server/websocket-server:${{ github.sha }}"
          echo "Building image: $IMAGE_NAME"

          # Ensure Docker is authenticated
          gcloud auth configure-docker australia-southeast2-docker.pkg.dev

          # Set up Buildx
          docker buildx create --use || true
          docker buildx inspect --bootstrap

          # Build and push
          docker buildx build \
            --platform=linux/amd64 \
            --file src/websocket-server/Dockerfile \
            --tag "$IMAGE_NAME" \
            --push \
            .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # ✅ Step 5: Terraform Init
      - name: Terraform Init
        working-directory: terraform/websocket-server
        run: terraform init

      # ✅ Step 6: Terraform Apply
      - name: Terraform Apply
        working-directory: terraform/websocket-server
        run: |
          terraform apply -var="image_tag=australia-southeast2-docker.pkg.dev/q-manager-453001/websocket-server:${{ github.sha }}" \
                          -var="mongo_uri=${{ secrets.MONGO_URI }}" \
                          -var="env=qa" \
                          -var="project_id=q-manager-453001" \
                          -var="region=australia-southeast2" \
                          -auto-approve
