name: Deploy WebSocket Server to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "src/websocket-server/**"
      - "terraform/websocket-server/**"
      - ".github/workflows/deploy-websocket-server.yml"

env:
  REGION: australia-southeast2
  PROJECT_ID: q-manager-453001
  REPO_PATH: q-manager-websocket-server
  IMAGE_NAME: websocket-server
  FULL_IMAGE: australia-southeast2-docker.pkg.dev/q-manager-453001/q-manager-websocket-server/websocket-server

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push WebSocket Docker Image
        run: |
          echo "Building image: $FULL_IMAGE:${{ github.sha }}"
          docker buildx build \
            --platform=linux/amd64 \
            --file src/websocket-server/Dockerfile \
            --tag "$FULL_IMAGE:${{ github.sha }}" \
            --push \
            .

  deploy:
    name: Deploy to Cloud Run with Terraform
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform/websocket-server
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/websocket-server
        run: |
          terraform apply \
            -var="image_tag=${{ env.FULL_IMAGE }}:${{ github.sha }}" \
            -var="mongo_uri=${{ secrets.MONGO_URI }}" \
            -var="env=qa" \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -auto-approve
