name: Deploy Next.js App to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "/**"
      - "Dockerfile"
      - "terraform/nextjs/**"
      - ".github/workflows/deploy-nextjs.yml"
      - "!src/websocket-server/**"
      - "!terraform/websocket-server/**"
      - "!.github/workflows/deploy-websocket-server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Build Args
        run: |
          echo "BUILD ARGS FROM SECRETS"
          echo "NEXT_PUBLIC_MONGO_URI=${{ secrets.MONGO_URI }}"

      - name: Debug Clerk Build Args
        run: |
          echo "BUILD ARGS FROM SECRETS"
          echo "CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      # ✅ FIX: Authorize Docker to push to Artifact Registry
      - name: Configure Docker to Use Google Cloud Credentials
        run: |
          gcloud auth configure-docker australia-southeast2-docker.pkg.dev

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "q-manager-453001"

      # ✅ Set up Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Create Buildx Builder
      - name: Create Buildx Builder
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      # ✅ Debug Buildx Context
      - name: Debug Buildx Context
        run: |
          docker buildx ls

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="australia-southeast2-docker.pkg.dev/q-manager-453001/q-manager-nextjs/nextjs-app:${{ github.sha }}"
          docker buildx build --platform=linux/amd64 \
            --build-arg NEXT_PUBLIC_MONGO_URI="${{ secrets.MONGO_URI }}" \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.CLERK_PUBLISHABLE_KEY }}" \
            -t "$IMAGE_NAME" -f Dockerfile . --push

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform/nextjs-app
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/nextjs-app
        run: |
          terraform apply -var="image_tag=australia-southeast2-docker.pkg.dev/q-manager-453001/q-manager-nextjs/nextjs-app:${{ github.sha }}" \
                          -var="project_id=q-manager-453001" \
                          -var="region=australia-southeast2" \
                          -var="mongo_uri=${{ secrets.MONGO_URI }}" \
                          -var="clerk_publishable_key=${{ secrets.CLERK_PUBLISHABLE_KEY }}" \
                          -var="gcloud_service_key='${{ secrets.GCLOUD_SERVICE_KEY }}'" \
                          -lock-timeout=90s \
                          -auto-approve
